### ISSUE TITLE
Pls add new bus route 47

### ISSUE THREAD

**Issue by peterj71** [cheeaun/busrouter-sg#16] opened 2016-02-04 05:42 UTC
Changi Business Park - Amber Road loop service

**Comment by silencer22** [comment] 2016-02-04 15:00
just checking, mayb cheeaun would like to share how do you compile the data for your app?
Would like to help to update them

**Comment by cheeaun** [comment] 2016-02-04 16:32
Closing this due to duplicate of #15

**Closed by cheeaun** 2016-02-04 16:32 UTC
